name: React CI/CD

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master # Trigger on pull requests targeting the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Clones the repository

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your desired Node.js version

      - name: Install dependencies
        run: npm install # Or yarn install if you're using Yarn

      - name: Run tests
        run: npm test # Or yarn test

      - name: Build React application
        run: npm run build # Or yarn build
